### PR TITLE
Adding export Bind file feature

### PR DESCRIPTION
**Pull request by paddy667**

### CODE REVIEW

**Comment by mahtin** [comment]
I just added _export_ into the 1.7.2 release. It's also in the documentation (in 1.7.3). It needed (as you realized) some changes to the JSON processing - which in the works anyway for other reasons.

**Comment by paddy667** [comment]
Thanks @mahtin, my pull request was a bit of a mess here (hence why I closed it), I'm interested to know how you tackled the JSON processing so I'm going to have a look. 

Thanks again
Paddy

**Comment by mahtin** [comment]
It wasn't much code; but it too some thinking about. It's a two part thing. First off; see if the response was plain text (which is what ```dns_records/export``` uses)
```
            elif response_type == 'text/plain' or response_type == 'application/octet-stream':
```
Then place the single string into the results that are returned. This would normally be a JSON object or array.
```
                    if response_code == requests.codes.ok:
                        # 200 ok
                        response_data = {'success': True, 'result': str(response_data)}
                    else:
```
What I'm relying on is the [JSON spec](http://www.json.org) says the response can be an object, an array or a value.

Hence, when you run the following command:
```
zone="example.com" ; or whatever
cli4 /zones/:${zone}/dns_records/export | jq -r .
```
You get a valid response (there's no additional code within cli4 or any user written .py code. What's unclear is if the code above should also include the mapping of newlines, tabs etc into their real values with the Cloudflare module. I don't think it should. What's there presently returns valid JSON. It just so-happens that you need to map from JSON to text if you know you are calling a text based API endpoint (presently ```dns_records/export``` is the only endpoint like this. That mapping is the ```-r``` option to [jq](https://stedolan.github.io/jq/).

Hope that helps.

**Comment by mahtin** [comment]
@paddy667 - two things.
1. Please use [python-cloudflare](https://github.com/cloudflare/python-cloudflare) repository for these issues as that's the full repository.
2. I added [example_dns_export.py](https://github.com/cloudflare/python-cloudflare/blob/master/examples/example_dns_export.py) which shows that Python (and JSON) is pretty clever about these things. It just works correctly.

Hope that helps.

**Pull request closed without merging**
